services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:2.19.2
    restart: unless-stopped
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      - WEBHOOK_URL=https://n8n.app.codeloop.eu/
      - TZ=Europe/Warsaw
      - GENERIC_TIMEZONE=Europe/Warsaw
      - N8N_SECURE_COOKIE=true
    volumes:
      - n8n_data:/home/node/.n8n
volumes:
  n8n_data:
