services:
  ollama:
    image: ollama/ollama:0.22.0
    restart: unless-stopped
    volumes:
      - ollama_storage:/root/.ollama
    networks:
      - dokploy-network

  init-ollama:
    image: ollama/ollama:0.22.0
    depends_on:
      - ollama
    volumes:
      - ollama_storage:/root/.ollama
    entrypoint: /bin/sh
    environment:
      - OLLAMA_HOST=ollama:11434
    command:
      - "-c"
      - "sleep 30; ollama pull llama3.2:3b; ollama pull gemma4:e4b; ollama pull gemma3:4b; ollama pull gemma3n:e4b"
    networks:
      - dokploy-network

volumes:
  ollama_storage:

networks:
  dokploy-network:
    external: true
