services:
  lgtm:
    image: grafana/otel-lgtm:0.24.0
    volumes:
      - lgtm-data:/data
      - ./otelcol-config.yaml:/otel-lgtm/otelcol-config.yaml:ro
    environment:
      PROMETHEUS_EXTRA_ARGS: "--storage.tsdb.retention.time=10d --storage.tsdb.retention.size=5GB"
      ENABLE_LOGS_ALL: false
    networks:
      - dokploy-network
    restart: unless-stopped

volumes:
  lgtm-data:

networks:
  dokploy-network:
    external: true
